AllCops:
  Exclude:
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'Guardfile'
    - 'Gemfile'
    - '*.gemspec'
    - 'Rakefile'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
